version: '3.8'
services:
  dev:
    build:
      context: ..
      dockerfile: container/Dockerfile.dev
    image: knowledge-dev:latest
    container_name: knowledge-dev
    volumes:
      - ..:/app:Z
      - ${HOME}/.config/Code/User/instructions:${HOME}/.config/Code/User/instructions:Z
      - ${HOME}/.config/Code/User/prompts:${HOME}/.config/Code/User/prompts:Z
    working_dir: /app
    command: ["zsh"]
    tty: true
    stdin_open: true
