# Knowledge Archival System Configuration

# System settings
system:
  name: "Knowledge Archival System"
  version: "0.1.0"

# Paths configuration
paths:
  data_dir: "data"
  backup_dir: "backup"
  log_dir: "logs"

# Wikipedia source settings
wikipedia:
  enabled: true
  data_dir: "data/wikipedia"
  backup_dir: "backup/wikipedia"
  download_url: "https://download.kiwix.org/zim/wikipedia/wikipedia_en_all_maxi.zim"
  kiwix_library_url: "https://library.kiwix.org/library/library_zim.xml"
  # How often to check for updates (in days)
  check_interval: 7
  # Maximum number of backups to keep
  max_backups: 3

# Metrics configuration
metrics:
  enabled: true
  port: 9090

# Logging configuration
logging:
  level: "INFO"
  max_size_mb: 10
  backup_count: 5
